### ISSUE TITLE
Is oscillation mitigated in generalized centrifugal force Model (GCFM)

### ISSUE THREAD

**Issue by godisreal** [chraibi/sfm-oscillation#4]
Is oscillation mitigated in generalized centrifugal force Model (GCFM)? 
It is better to compare generalized centrifugal force with social force.  I also have two questions about your GCFM.   
1. Is the oscillation mitigated due to v_ij (relative velocity from i to j) in GCFM?  
2. What is the role of v0 in GCFM?  
Thank you very much.

**Comment by chraibi** [comment]
I did not make the calculations to check. Feel free to do it. Would be interesting to know how GCFM handles oscillations. 



> Is the oscillation mitigated due to v_ij (relative velocity from i to j) in GCFM?

Again, I think it should be properly checked by doing the calculations.



> What is the role of v0 in GCFM?

Although not related to this repository, but its ment to compensate for v0 in the driving force.

**Comment by godisreal** [comment]
OK.  I change the code as below to test GCFM.  
`f_rep = -(1.0/dist)*(eta*v0-beta*dx_m+beta*dx_n)**2
eta=1.0
beta=0.3
The result is illustrated as below.  Oscillation is mitigated significantly.  
BTW, is there any coefficient before vij in GCFM?  I suppose there should be.  
Comments are much welcome.  
![osc_eta1 0_beta0 3](https://user-images.githubusercontent.com/13465534/65319952-66282480-dbd3-11e9-9213-7f872879a1ed.png)

**Comment by chraibi** [comment]
Nice result. Thank you for your efforts. Maybe you could figure out which component in the model is directly responsible for this damping effect and would care to share. :-)

>  BTW, is there any coefficient before vij in GCFM? I suppose there should be.

In the original model there is no coefficient. This is the equation from the [paper](https://arxiv.org/pdf/1008.4297.pdf)

<img width="249" alt="Screenshot 2019-09-23 08 27 10" src="https://user-images.githubusercontent.com/5772973/65405365-619b8000-de0e-11e9-81cc-13cd3fc089ea.png">

**Comment by godisreal** [comment]
OK.  I read your paper.  I realize that the force component of v_ij is not effective if individual j is moving away from i (vij.eij<0).  So the code is slightly modified as below to compare oscillation of social force model and GCFM.  

```
        f_rep = -(1.0/dist)*(eta*v0+beta*np.maximum((dx_n-dx_m),0.0))**2
```
As beta increase, oscillation is mitigated while convergence time increases.  I got the testing result for beta =1.0, which is exactly the same as the formula in the paper.  However, the result is not as good as beta=0.3 because it takes more time to converge to steady state.  

I think it is v_ij that offsets oscillation.  This could be explained by ODE or control theory.  
BTW, I consider writing a brief document to compare social force with other forces such as GCF.  If so, I should mention you somewhere or invite you as co-author if you would like.

**Comment by chraibi** [comment]
I'm happy to contribute. Just drop me a Mail at m.chraibi@fz-juelich.de
